### ISSUE TITLE
container.xml must be in a dir named META-INF

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/nikolai-gogol_dead-souls#1]

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/nikolai-gogol_dead-souls/commit/456e589cdd7056674cf9aa9dbc8f9e2b9e84f87d. Incidentally, `create-draft` set it up like this originally, and still does when I just tested it. Will file an issue.

**Comment by acabal** [comment]
[Looks like it's implicitly created by `cp -r`](https://github.com/standardebooks/tools/blob/master/create-draft#L123), maybe that behaves differently on different platforms?
