### ISSUE TITLE
Chapters should be wrapped in parent part <section>, and use <h3> for titles

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/nikolai-gogol_dead-souls#2]
Each chapter should be wrapped in

`<section id="part-1" epub:type="part">`

or

`<section id="part-2" epub:type="part">`

These should be direct children of the `<body>` tag.  Then, chapter titles should be `<h3>` instead of `<h2>` (since part-1.xhtml and part-2.xhtml are `<h2>`)

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/nikolai-gogol_dead-souls/commit/1c4599907b36c3de832b2af52eeed62194582cfd
