### ISSUE TITLE
Translator must be included in <dc:identifier> 

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/nikolai-gogol_dead-souls#3]
So, the identifier should be: url:https://standardebooks.org/ebooks/nikolai-vasilievich-gogol/dead-souls/d-j-hogarth

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/nikolai-gogol_dead-souls/commit/6e6551f7a26226ca5ae883ef68160cbafb1da34b
