### ISSUE TITLE
"Nikolai Gogol" instead of "Nikolai Vasilievich Gogol"

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/nikolai-gogol_dead-souls#4]
I think "Nikolai Gogol", without the middle name, is how he's more commonly known in English-language publications.  Just like we talk about "Anton Chekhov" and not "Anton Pavlovich Chekhov", and "Leo Tolstoy" and not "Graf Lev Nikolayevich Tolstoy".

This can probably be just a quick find-and-replace through the whole ebook.  Note this will also change the <dc:indentifier> in content.opf, and titlepage.svg

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/nikolai-gogol_dead-souls/commit/44c4d5ca55b9368dda97156a27954861b9a19ee5. I also renamed the repo to reflect this.
