### ISSUE TITLE
Height of titlepage.svg is off

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/nikolai-gogol_dead-souls#5]
In order to center the titlepage SVG on the page, its height must be no more than the contents.  You can copy and paste the height and other details from https://github.com/standardebooks/anton-chekhov_short-fiction_constance-garnett/blob/master/images/titlepage.svg which has the same format as this one.

**Comment by robinwhittleton** [comment]
Fixed by https://github.com/robinwhittleton/nikolai-gogol_dead-souls/commit/7a75d0bf115015867d2aa66c4d8e770193e1f7a0
