### ISSUE TITLE
Complete imprint.xhtml

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/nikolai-gogol_dead-souls#7]
All we need to do is fill in the PG link and Google Books/Hathi Trust link.  (And change the text from Hathi Trust if we used Google Books.)

**Comment by robinwhittleton** [comment]
Fixed by https://github.com/robinwhittleton/nikolai-gogol_dead-souls/commit/7a75d0bf115015867d2aa66c4d8e770193e1f7a0
