### ISSUE TITLE
Parts and chapters in wrong <li> in toc.xhtml

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/nikolai-gogol_dead-souls#8]
The `<li>` items for parts and chapters should be in a new `<ol>` item *within* the `<li>` item that contains the link to the half title.  See https://github.com/standardebooks/max-beerbohm_zuleika-dobson/blob/master/src/epub/toc.xhtml for an example of this.

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/nikolai-gogol_dead-souls/commit/f255d72c72cf5c6e5081e48743a58f30522c4c23
